### ISSUE TITLE
Mono_dense_reconstruction dependency

### ISSUE THREAD

**Issue by laxnpander** [ethz-asl/aerial_mapper#10]
Hey there,

I am currently trying to install aerial_mapper. However as I follow the installation steps following error appears:

Exception caught during install: Error processing 'ethzasl_brisk' : [ethzasl_brisk] Checkout of git@github.com:ethz-asl/ethzasl_brisk.git version None into /home/lachs/Documents/Workspace/catkin_ws/aerial_mapper/src/ethzasl_brisk failed.
Error processing 'mono_dense_reconstruction' : [mono_dense_reconstruction] Checkout of git@github.com:ethz-asl/mono_dense_reconstruction.git version None into /home/lachs/Documents/Workspace/catkin_ws/aerial_mapper/src/mono_dense_reconstruction failed.

Sounds to me like the mono dense reconstruction dependency currently does not allow me to run the framework?

Thanks for an info in advance and best regards,

Alex

**Comment by hitimo** [comment]
Hi @laxnpander 

This is true, I had added a comment about this dependency here:
https://github.com/ethz-asl/aerial_mapper/tree/master/aerial_mapper_dense_pcl

We are currently waiting for the notification of a submitted paper before we can open-source the mono dense reconstruction pipeline. This should happen within the next weeks.

In the meantime, such that you can use the complete framework already now, I will add my own implementation of a stereo dense reconstruction. So my implementation simply uses the two time consecutive images for the reconstruction. In contrast, the mono dense reconstruction pipeline keeps a buffer of N poses and selects the optimal combination of poses for a minimal depth uncertainty. 

Hope this helps,
Timo

**Comment by laxnpander** [comment]
@hitimo 
That would be awesome, thank you!

**Comment by laxnpander** [comment]
@hitimo 
After some time passing, I came back to try. What do I need to do, to get your own implementation? Following the proposed install process is not working.
Thanks for your help and best regards,

Alex

**Comment by RicardoRagel** [comment]
Hi @hitimo and @laxnpander

I am in the same situation of Alex, any progress in open-source or the link to your own implementation?

Thanks in advance!

**Comment by laxnpander** [comment]
@RicardoRagel : I think it is at least in the GitHub version now. Not sure if you must change something in the install instructions (probably). I’ll try it in the next few days

**Comment by RicardoRagel** [comment]
@laxnpander : Thank you for your answer, Alex. You are right, if you follow the current instructions, at `'$wstool update -j8'` you still receive the error: 

`ERROR in config: Error processing 'mono_dense_reconstruction' : [mono_dense_reconstruction] Checkout of git@github.com:ethz-asl/mono_dense_reconstruction.git <...>`

I have checked that logically _mono_dense_reconstruction_ is still present in _/src/aerial_mapper/install/dependencies.rosinstall_, so I assume that it must be changed by the @hitimo implementation. Do you know what and where is this implementation? Have you tried to install it again?

Thank you!

**Comment by laxnpander** [comment]
@RicardoRagel : Ah jeah, you are right. I scanned through the implementation and saw "SBGM", which is also the standard OpenCV dense stereo algorithm. I assumed he might have used that as spare implementation, but it still definitely depends on files that don't exist in this repo and can't be pulled. Therefore we will need to wait I guess :)

**Comment by hitimo** [comment]
Please see #17. Sorry for the delay.
