### ISSUE TITLE
failed to install on ubuntu 16

### ISSUE THREAD

**Issue by riyueshi** [ethz-asl/aerial_mapper#11]
Hi,
  I'm not familiar with Linux, while I follow the installation step I stuck with this step "catkin config --extend /opt/ros/indigo". It seem indigo only available on Ubuntu 14. Does this means this project could only run on Ubuntu 14? Is there any tips for installation on Ubuntu.

Miller

**Comment by hitimo** [comment]
Hi @riyueshi 
you can also use a newer ROS distribution; you only need to replace `indigo` in `catkin config --extend /opt/ros/indigo` by the version name, e.g. `kinetic`. For installing ROS kinetic, you can follow the installation guidelines: http://wiki.ros.org/kinetic/Installation/Ubuntu

**Comment by riyueshi** [comment]
thanks for your quick reply, I got another problem: I got lots of fatal error while perform"wstool update -j8" as following: 
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[grid_map] still active
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


By the way,  I also failed to execute "git clone git@github.com:ethz-asl/aerial_mapper.git" but this is fixed by "git clone https://github.com/ethz-asl/aerial_mapper.git"

**Comment by hitimo** [comment]
You have to set up your SSH key as described here: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
This should solve the errors and you can also use `git clone git@github.com:ethz-asl/aerial_mapper.git`

**Comment by riyueshi** [comment]
Thanks! all steps works now. Is there any schedule for "the mono dense reconstruction pipeline"
