### ISSUE TITLE
about the Real-time mosaic

### ISSUE THREAD

**Issue by riyueshi** [ethz-asl/aerial_mapper#12]
Hi, @hitimo 
  I read the code and try to find out how to implement realtime orthomosaic. But I failed to find how to update the DSM according to a increasing point clound, and how to update the finial orthophoto. the pipeline implement in "ortho-backward-grid.cc" and "ortho-from-pcl.cc" seem a non realtime one since they using all the image, poses  and point cloud. And the implement in "ortho-forward-homography.cc" could handle the realtime case, but it is not the real orthophoto since it didn't use the terrain information. Did I missed some thing that could make the first two pipeline process in realtime? 

And one more question about the implement of  "ortho-forward-homography.cc". In this pipeline, I think the key point is to find the corespondents between the four image corner points and ground points, the easiest way is using the average height of the scene as projection planes. in the ortho-forward-homography line 98, the scale is computed using a constant number 414. I can't understand what this constant number means, could you give me some tips to understand the way to compute the scale.

Miller

**Comment by hitimo** [comment]
Hi @riyueshi 

you can find a demo for the incremental `ortho-backward-grid` here: https://github.com/ethz-asl/aerial_mapper/blob/master/aerial_mapper_demos/src/ortho/main-ortho-backward-grid-incremental.cc#L112-L140
This takes one image-pose pair at a time and processes the modules incrementally.

> In this pipeline, I think the key point is to find the corespondents between the four image corner points and ground points, the easiest way is using the average height of the scene as projection planes. in the ortho-forward-homography line 98, the scale is computed using a constant number 414. 

Indeed, that is the average height of the ground plane for the real-world dataset ["Rafz"](https://github.com/ethz-asl/aerial_mapper/wiki/How-to-run) 
I am currently working on a clean-up of the code where e.g. this is exported as a parameter.

**Comment by riyueshi** [comment]
Thanks! All things are clear now. 
I just read your paper "Mapping on the Fly: Real-time 3D Dense Reconstruction, Digital Surface Map and Incremental Orthomosaic Generation for Unmanned Aerial Vehicles". This helped a lot to  understand the code. And I am doing some research on the accuracy of orthophoto recently. In the paper, Fig.6 mentioned a measures 400.96m for proposed and 401.28m  for satellite. As far as I know the accuracy of raw GPS has very strong influence to the accuracy of orthophoto without the help of ground control point. Is there any information about the accuracy of raw GPS for that dataset used in the paper?Is it a normal GPS equipped on the drone or an RTK GPS?

**Comment by hitimo** [comment]
The type of GPS receiver is mentioned in the paper: `ublox LEA-6H`. So "normal" GPS and no RTK/DGPS.
