### ISSUE TITLE
aerial_mapper fail to install under Ubuntu 14.04

### ISSUE THREAD

**Issue by yjmenezes** [ethz-asl/aerial_mapper#16]
Dear All.

I am trying to install aerial_mapper following Timo Hinzmann directions.  ( thx you )

ROS steps are ok;
catkin_make is installed under /opt/ros/indigo/bin/

I just change this:

git clone https://github.com/ethz-asl/aerial_mapper.git

i can not run:
catkin init
catkin config
....

i will apreciate any help;

regards,
julio
PS: Debian 9.x steps will be  appreciated

**Comment by hitimo** [comment]
Hi @yjmenezes 

> i can not run:
catkin init
catkin config
....

What concrete error message(s) do you get?

**Comment by yjmenezes** [comment]
Hi @hitimo 

thank you for your reply and thx all aerial_mapper developers.
I am trying to figure out why catkin is not built.
I compile under Ubuntu 14.04.5 LTS  x64, 32GB RAM

catkin alone  did not appear inside /opt/ros/indigo/bin
catkin_make, catkin_find  and some other are there but not catkin alone.
My environment is ok,  export | grep ROS shows several paths.

I have a small dataset + LiDAR data and i would like to test it with aerial_mapper.

julio

**Comment by hitimo** [comment]
I see, you are probably missing
```
sudo apt-get install python-wstool python-catkin-tools
```

which installs the `catkin build` binary.

I updated the wiki:
https://github.com/ethz-asl/aerial_mapper/wiki/How-to-install

**Comment by yjmenezes** [comment]
Hi @hitimo 

thank you again.

The new steps are better but i could not sussed. The catkin alone is solved.
It seems i have some authentication issue.
Here are two screenshots and a log.
![aerial_mapper_2018-01-19 08-45-04](https://user-images.githubusercontent.com/4775645/35170708-43a1eb0a-fd48-11e7-90aa-e13df9b3a941.png)
![aerial_mapper-2018-01-19 18-33-32](https://user-images.githubusercontent.com/4775645/35170710-468aa6ea-fd48-11e7-8997-a9b7abc6aaf3.png)
[amapper_log.zip](https://github.com/ethz-asl/aerial_mapper/files/1647866/amapper_log.zip)

thx,
julio
btw, i upload to my git a church+LiDAR dataset:

**Comment by hitimo** [comment]
Make sure you have your SSH keys set-up as described here: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ This should solve the errors. Also have a look here: #11

> btw, i upload to my git a church+LiDAR dataset:

Thanks for the info, I'll check it out.

**Comment by yjmenezes** [comment]
@hitimo 

I apologise, i forgot to copy my credentials from my Debian host to  QEMU Ubuntu14.04 guest.

I got some warnings but the  wiki  installation directions are ok.

I add  gfortran  package, because i saw some warning during compilation.

Now it is time to learn how to run aerial_mapper.

thank you.
![aeriam_mapper_2018-01-20](https://user-images.githubusercontent.com/4775645/35188397-d379820a-fe1b-11e7-9406-2102d60a9e80.png)
