### ISSUE TITLE
Configure the catkin source space

### ISSUE THREAD

**Issue by RicardoRagel** [ethz-asl/aerial_mapper#18]
Hi @hitimo 

I had found a possible problem in the installation instructions (maybe only for me, but I am not sure, so I think is good to tell you). The 'catkin init' command does not configure the source space (where the code is), so 'catkin build aerial_mapper' does not work. To solve it execute first:

`catkin config --source-space /home/deltanet/catkin_ws_aerial_mapper/src/`

Hope it is helpful :)

**Comment by RicardoRagel** [comment]
Idem for build and devel spaces

**Comment by hitimo** [comment]
> The 'catkin init' command does not configure the source space

What happened if you type `cd /home/deltanet/catkin_ws_aerial_mapper && catkin init`? Potentially there is a catkin_ws initialised at a higher-level directory, i.e. make sure that there is no folder `.catkin_tools` under `/home/deltanet/`

**Comment by RicardoRagel** [comment]
Yes, maybe a old `.catkin_tools` exists from a previous wrong installation. Thank you!
