### ISSUE TITLE
Error launching demos

### ISSUE THREAD

**Issue by RicardoRagel** [ethz-asl/aerial_mapper#20]
Hi!

After download "How to run" datasets and launch the example:

 `$ roslaunch aerial_mapper_demos 0-synthetic-cadastre-dsm.launch`

I receive the next errors:

<...>

I0119 14:33:48.566270  9198 aerial-mapper-io.cc:255] Loading camera calibration from: /home/deltanet/datasets/cadastre_gray/camera_fixed_wing.yaml
W0119 14:33:48.566978  9198 ncamera-yaml-serialization.cc:30] **Unable to get the id for the ncamera. Generating new random id.**
W0119 14:33:48.567148  9198 camera-yaml-serialization.cc:131] Unable to get the id for the camera. Generating new random id.
I0119 14:33:48.567246  9198 aerial-mapper-io.cc:40] Loading body poses via format: 0
I0119 14:33:48.567255  9198 aerial-mapper-io.cc:107] Loading body poses from: /home/deltanet/datasets/cadastre_gray/opt_poses.txt
I0119 14:33:48.568365  9198 aerial-mapper-io.cc:120] T_G_Bs->size() = 428
I0119 14:33:48.568382  9198 aerial-mapper-io.cc:211] Loading images from directory+prefix: /home/deltanet/datasets/cadastre_gray/image_
*** **Aborted at 1516368828 (unix time) try "date -d @1516368828" if you are using GNU date** ***
PC: @     0x7f44409ecd20 cv::_InputArray::size()
*** SIGSEGV (@0x1010028) received by PID 9198 (TID 0x7f444195ba40) from PID 16842792; stack trace: ***
    @     0x7f443f44ccb0 (unknown)
    @     0x7f44409ecd20 cv::_InputArray::size()
    @     0x7f443c8fb61e cv::imshow()
    @     0x7f4440f8f824 io::AerialMapperIO::loadImagesFromFile()
    @           0x4034da main
    @     0x7f443f437f45 __libc_start_main
    @           0x403b93 (unknown)
pci id for fd 24: 8086:5927, driver (null)
[intel_init_bufmgr:1091] Error initializing buffer manager.
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
[demo_dsm-3] process has died [pid 9198, exit code -11, cmd /home/deltanet/catkin_ws_aerial_mapper/devel/lib/aerial_mapper_demos/aerial_mapper_demos_dsm --flagfile=/home/deltanet/catkin_ws_aerial_mapper/src/aerial_mapper/aerial_mapper_demos/flags/0-synthetic-cadastre-dsm.ff __name:=demo_dsm __log:=/home/deltanet/.ros/log/6103b1d6-fd1d-11e7-9de5-f44d306d9b3e/demo_dsm-3.log].
log file: /home/deltanet/.ros/log/6103b1d6-fd1d-11e7-9de5-f44d306d9b3e/demo_dsm-3*.log
[ERROR] [1516368828.980968065]: PluginlibFactory: The plugin for class 'grid_map_rviz_plugin/GridMap' failed to load.  Error: **Could not find library corresponding to plugin grid_map_rviz_plugin/GridMap**. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.

<...>

Any idea about these?

Thanks!

**Comment by RicardoRagel** [comment]
Hi and thanks for the changes and the support @hitimo!

I have seen the changes in the last commit and in the installation instructions. There is only one problem: In the installation instructions, maybe the order must be: First `wstool update -j8` and later `sed -i ... opencv3_catkin/CMakeLists.txt`

The `0-synthetic-cadastre-dsm.launch` works perfectly now! The accumulated point cloud looks very nice :)

On the other hand, the `1-real-rafz-ortho-from-homography.launch` looks like it that does not work correctly. When I launch it, the rafz_gray dataset is load correctly and the node shows the sequence of images, but no homography result is shown and the program fails in:

```
I0122 10:23:54.483240  4905 aerial-mapper-io.cc:226] Number of images loaded: 249
*** Aborted at 1516613034 (unix time) try "date -d @1516613034" if you are using GNU date ***
PC: @     0x7f4af791e712 ortho::OrthoForwardHomography::prepareBlenderForNextImage()
*** SIGSEGV (@0x0) received by PID 4905 (TID 0x7f4af7cd6800) from PID 0; stack trace: ***
    @     0x7f4af54a7cb0 (unknown)
    @     0x7f4af791e712 ortho::OrthoForwardHomography::prepareBlenderForNextImage()
    @     0x7f4af791f75b ortho::OrthoForwardHomography::OrthoForwardHomography()
    @           0x402361 main
    @     0x7f4af5492f45 __libc_start_main
    @           0x4031f7 (unknown)
[demo_ortho_forward_homography-2] process has died
```
Maybe it has a similar opencv problem?

Thanks and great work!

**Comment by immuhammadadil** [comment]
HI, I am trying to run demo but its giving :error:[Failed to load NCamera from file /tmp/simulation/camera_fixed_wing.yaml with the error: bad file]
Only blank GUI is opening with empty grid in center
