### ISSUE TITLE
glog_catkin build error

### ISSUE THREAD

**Issue by grzlr** [ethz-asl/aerial_mapper#26]
Hello,

While building the package, I encountered the following error: 
`Errors     << glog_catkin:make /path/to/catkin_ws_aerial_mapper/logs/glog_catkin/build.make.000.log                                                                                                                                 
/bin/sh: 1: autoreconf: not found
make[2]: *** [glog_src-prefix/src/glog_src-stamp/glog_src-configure] Error 127
make[1]: *** [CMakeFiles/glog_src.dir/all] Error 2
make: *** [all] Error 2`

This was fixed by installing autoconf on Ubuntu 16.04:
`$sudo apt install autoconf`

**Comment by hitimo** [comment]
@grzlr Thanks a lot for reporting, I added it to the install instructions:
https://github.com/ethz-asl/aerial_mapper/wiki/How-to-install
