### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by sadu** [ethz-asl/aerial_mapper#28]
Ubuntu 16.04 fresh install with ROS kinetic. I followed steps from readme and while executing the command `roslaunch aerial_mapper_demos 0-synthetic-cadastre-dense-pcl.launch
` the following error message is shown. What could be wrong here?
p.s. I am new to ROS/catkin

```
Finished  <<< aerial_mapper_demos                          [ 59.1 seconds ]                                  
[build] Summary: All 31 packages succeeded!                                                                  
[build]   Ignored:   22 packages were skipped or are blacklisted.                                            
[build]   Warnings:  13 packages succeeded with warnings.                                                    
[build]   Abandoned: None.                                                                                   
[build]   Failed:    None.                                                                                   
[build] Runtime: 1 hour 4 minutes and 15.6 seconds total.                                                    
[build] Note: Workspace packages have changed, please re-source setup files to use them.
mapper@mapper-VirtualBox:~/catkin_ws_aerial_mapper/src$ roslaunch aerial_mapper_demos 0-synthetic-cadastre-dense-pcl.launch
[0-synthetic-cadastre-dense-pcl.launch] is neither a launch file in package [aerial_mapper_demos] nor is [aerial_mapper_demos] a launch file name
The traceback for the exception was written to the log file

```

**Comment by sadu** [comment]
`source ../devel/setup.bash` is required after `catkin build aerial_mapper` to run the demos, fixes my issue

**Comment by immuhammadadil** [comment]
Hi,
kindly guide about running custom dataset. My system cant find ROS nodes.
Error is here:
ERROR: cannot launch node of type [aerial_mapper_demos/aerial_mapper_demos_dense_pcl]: can't locate node [aerial_mapper_demos_dense_pcl] in package [aerial_mapper_demos]

I have set path of dataset in config file

**Comment by acfloria** [comment]
See the previous question. You have to source your workspace after the build.
