### ISSUE TITLE
Why do you use 3D k-d tree for 2D grid?

### ISSUE THREAD

**Issue by laxnpander** [ethz-asl/aerial_mapper#29]
Hey hey,

I stumbled upon you DSM creation and wonder why you use a 3D k-d tree for nearest neighbourhood search? In my thinking, for each cell you want to find the points closest to this cells x- and y-coordinate. Therefor you should only search your point cloud for the closest points in x- and y-direction. If you also consider the point cloud's z-axis, you might get wrong neighbours in regions with rapid elevation changes.

I'll try to visualize it with ASCII: Given the points (0,0,0), (1,0,0), (2,0,0), (3,0,5), (4,0,5), (5,0,0):
...''. 
the nearest neighbours for point (2,0,0) close to the elevation change should be (3,0,5). However, if you also consider the height, it will detect (5,0,0) as closer. Or am I overlooking something?

Best regards,
Alex

**Comment by hitimo** [comment]
Hi Alex

Thanks a lot for your question. Yes, only the distance in x,y should be considered. For the DSM, the 2D kd-tree is set up here: https://github.com/ethz-asl/aerial_mapper/blob/master/aerial_mapper_dsm/include/aerial-mapper-dsm/dsm.h#L58-L62

I implemented a simple test with your example points here:
https://github.com/ethz-asl/aerial_mapper/blob/test/kd-tree/aerial_mapper_utils/test/test-kd-tree.cc
and imo it works as intended.

Example 1: NN search at (2.0,0) with search radius 1.5:
```
rosrun aerial_mapper_utils aerial_mapper_utils_test 
Query point x/y/z: 2/0/0 with search radius: 1.5
ID: 1, dist: 1, x/y/z/: 1/0/0
ID: 2, dist: 0, x/y/z/: 2/0/0
ID: 3, dist: 1, x/y/z/: 3/0/5
```
Example 2: NN search directly in between elevation change returns the closest point from the "ground" and from the "plateau":
```
rosrun aerial_mapper_utils aerial_mapper_utils_test 
Query point x/y/z: 2.5/0/0 with search radius: 0.5
ID: 2, dist: 0.25, x/y/z/: 2/0/0
ID: 3, dist: 0.25, x/y/z/: 3/0/5
```
Hope this helps.

**Comment by laxnpander** [comment]
Ah, I see. You feed the 3D point cloud, but limit the k-d tree dimension to 2u. That sounds reasonable, thanks for your explanation!
