### ISSUE TITLE
Found bug when running 0-synthetic-cadastre-ortho-from-pcl.launch

### ISSUE THREAD

**Issue by mdmosley1** [ethz-asl/aerial_mapper#33]
https://github.com/ethz-asl/aerial_mapper/blob/a57233db3628629dcd4b4c8b01c43d3ec6f560bc/aerial_mapper_demos/src/ortho/main-ortho-from-pcl.cc#L109

'point_cloud' is re-declared within the local scope of an else block. This line should be removed, or else the program crashes because CHECK(point_cloud.size() > 0) fails near the end of the program.

**Comment by hitimo** [comment]
Thanks a lot @mdmosley1
