### ISSUE TITLE
Host key verification failed. fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by immuhammadadil** [ethz-asl/aerial_mapper#36]
Above error comes while running following command
wstool update -j8

**Comment by rikba** [comment]
Either you need to set an [ssh key](https://help.github.com/en/articles/connecting-to-github-with-ssh) or use the [https rosinstall](https://github.com/ethz-asl/aerial_mapper/blob/master/install/dependencies_https.rosinstall).

**Comment by immuhammadadil** [comment]
HI, Thanks for the reply, tried to set up ssh key still getting the same problem: 
The authenticity of host 'github.com (192.30.253.113)' can't be established.
