### ISSUE TITLE
What does T_G_C and T_G_B stand for?

### ISSUE THREAD

**Issue by zzxp** [ethz-asl/aerial_mapper#37]
hi，I want to know that what  are T_G_C and T_G_B mean?
For example,Maybe T_G_C means from ground to camera?

**Comment by zzxp** [comment]
Also,T_C_B?

**Comment by hitimo** [comment]
Hi @zzxp 
In [this paper](http://timohinzmann.com/publications/iros_2016_hinzmann.pdf) I describe the transformations in more detail. We tried to have the same nomenclature than e.g. [maplab](https://github.com/ethz-asl/maplab) or [aslam_cv2](https://github.com/ethz-asl/aslam_cv2):

G: Global/World frame
C: Camera frame
B (identical to I): Body frame of the robot, coinciding with the IMU 
T_G_C: Pose of camera in global/world frame
T_G_B (identical to T_G_I): Pose of body/IMU in global/world frame 
T_C_B (identical to T_C_I): Camera-IMU transformation obtained from [Kalibr](https://github.com/ethz-asl/kalibr)

**Comment by zzxp** [comment]
Thank you!
