### ISSUE TITLE
Demo not running properly. error:[Failed to load NCamera from file /tmp/simulation/camera_fixed_wing.yaml with the error: bad file]

### ISSUE THREAD

**Issue by immuhammadadil** [ethz-asl/aerial_mapper#38]
While running the demo with command:
roslaunch aerial_mapper_demos 0-synthetic-cadastre-ortho-backward-incremental-colored.launch
Output is not according to the expectation. (Only empty grid is shown in GUI)
Following the output on command line with the error shown in last line.

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    demo_dsm (aerial_mapper_demos/aerial_mapper_demos_dsm)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [4903]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e941c264-9bef-11e9-ad9b-fcaa1401cbb0
WARNING: Metapackage "aerial_mapper" should not have other dependencies besides a buildtool_depend on catkin and exec_depends.
process[rosout-1]: started with pid [4916]
started core service [/rosout]
process[rviz-2]: started with pid [4924]
process[demo_dsm-3]: started with pid [4934]
I0701 16:03:53.128233  4934 aerial-mapper-io.cc:255] Loading camera calibration from: /tmp/simulation/camera_fixed_wing.yaml
E0701 16:03:53.128453  4934 ncamera.cc:48] Failed to load NCamera from file /tmp/simulation/camera_fixed_wing.yaml with the error: 
bad file
F0701 16:03:53.128576  4934 aerial-mapper-io.cc:258] Check failed: ncameras Could not load the camera calibration from: /tmp/simulation/camera_fixed_wing.yaml
*** Check failure stack trace: ***
    @     0x7fd0506e043d  google::LogMessage::Fail()
    @     0x7fd0506e2253  google::LogMessage::SendToLog()
    @     0x7fd0506dffcb  google::LogMessage::Flush()
    @     0x7fd0506e2c3e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd051eb255d  io::AerialMapperIO::loadCameraRigFromFile()
    @           0x403e82  main
    @     0x7fd04f5d0830  __libc_start_main
    @           0x404579  _start
[demo_dsm-3] process has died [pid 4934, exit code -6, cmd /home/burqstream/catkin_ws_aerial_mapper/devel/lib/aerial_mapper_demos/aerial_mapper_demos_dsm --flagfile=/home/burqstream/catkin_ws_aerial_mapper/src/aerial_mapper/aerial_mapper_demos/flags/0-synthetic-cadastre-dsm.ff __name:=demo_dsm __log:=/home/burqstream/.ros/log/e941c264-9bef-11e9-ad9b-fcaa1401cbb0/demo_dsm-3.log].
log file: /home/burqstream/.ros/log/e941c264-9bef-11e9-ad9b-fcaa1401cbb0/demo_dsm-3*.log
^C[rviz-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by yujiatay** [comment]
Hi, I believe this problem is caused by the dataset not being in the right location. The code expects the dataset to be found in `/tmp/simulation/`. You can either move the dataset to this location or change the config found under flags.

**Comment by immuhammadadil** [comment]
Hi, thanks for the reply. i have changed path in config. But still getting following error
ERROR: cannot launch node of type [aerial_mapper_demos/aerial_mapper_demos_ortho_from_pcl]: can't locate node [aerial_mapper_demos_ortho_from_pcl] in package [aerial_mapper_demos]

**Comment by immuhammadadil** [comment]
I found the solution by sourcing the bashrc after cmake. And by placing the dataset in right folder
