### ISSUE TITLE
Did not converge with max. iterations.

### ISSUE THREAD

**Issue by immuhammadadil** [ethz-asl/aerial_mapper#41]
adil@adil-Y11C:~/catkin_ws_aerial_mapper/src/aerial_mapper/aerial_mapper_demos/launch$ roslaunch aerial_mapper_demos 0-synthetic-cadastre-dsm.launch
WARNING: Metapackage "aerial_mapper" should not have other dependencies besides a buildtool_depend on catkin and exec_depends.
... logging to /home/adil/.ros/log/50d0adc8-c66b-11e9-95c3-d4258b48fcce/roslaunch-adil-Y11C-15182.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: Metapackage "aerial_mapper" should not have other dependencies besides a buildtool_depend on catkin and exec_depends.
started roslaunch server http://adil-Y11C:40771/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    demo_dsm (aerial_mapper_demos/aerial_mapper_demos_dsm)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [15192]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 50d0adc8-c66b-11e9-95c3-d4258b48fcce
WARNING: Metapackage "aerial_mapper" should not have other dependencies besides a buildtool_depend on catkin and exec_depends.
process[rosout-1]: started with pid [15203]
started core service [/rosout]
process[rviz-2]: started with pid [15206]
process[demo_dsm-3]: started with pid [15211]
I0824 17:33:05.637838 15211 aerial-mapper-io.cc:255] Loading camera calibration from: /home/adil/big/camera_fixed_wing.yaml
W0824 17:33:05.739182 15211 ncamera-yaml-serialization.cc:30] Unable to get the id for the ncamera. Generating new random id.
W0824 17:33:05.740208 15211 camera-yaml-serialization.cc:131] Unable to get the id for the camera. Generating new random id.
I0824 17:33:05.740765 15211 aerial-mapper-io.cc:40] Loading body poses via format: 0
I0824 17:33:05.740828 15211 aerial-mapper-io.cc:107] Loading body poses from: /home/adil/big/opt_poses.txt
I0824 17:33:05.747117 15211 aerial-mapper-io.cc:120] T_G_Bs->size() = 450
I0824 17:33:05.747232 15211 aerial-mapper-io.cc:211] Loading images from directory+prefix: /home/adil/big/image_
I0824 17:34:50.976186 15211 aerial-mapper-io.cc:226] Number of images loaded: 450
I0824 17:34:50.976429 15211 main-dsm.cc:86] Perform dense reconstruction using planar rectification.
W0824 17:34:53.944281 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.944631 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.944766 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.944880 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.944984 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945080 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945220 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945307 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945389 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945493 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945593 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945693 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945803 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.945905 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946000 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946074 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946143 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946211 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946278 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946346 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946411 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946482 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946557 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946624 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946698 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946768 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946833 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946907 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.946975 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947048 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947170 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947240 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947310 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947381 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947448 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947513 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947580 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947649 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.947924 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948093 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948184 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948321 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948437 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948573 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948676 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948767 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948856 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.948945 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949030 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949120 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949204 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949290 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949375 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949460 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949544 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949630 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949713 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949797 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949882 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.949970 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950057 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950140 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950230 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950318 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950402 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950489 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950575 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950664 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950748 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950832 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.950918 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.951002 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.951089 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.951174 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
W0824 17:34:53.951259 15211 distortion-equidistant.cc:170] Did not converge with max. iterations.
I0824 17:34:54.961812 15211 stereo.cpp:94] Processing image 9/450
I0824 17:34:54.961858 15211 stereo.cpp:94] Processing image 19/450
I0824 17:34:57.932658 15211 stereo.cpp:94] Processing image 29/450
I0824 17:35:14.332056 15211 stereo.cpp:94] Processing image 39/450
I0824 17:35:40.509380 15211 stereo.cpp:94] Processing image 49/450
I0824 17:35:54.209096 15211 stereo.cpp:94] Processing image 59/450
F0824 17:35:58.256014 15211 rectifier.cpp:100] Check failed: xyw_2(2) != 0.0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fdb85a11b0d  google::LogMessage::Fail()
    @     0x7fdb85a139b1  google::LogMessage::SendToLog()
    @     0x7fdb85a1163d  google::LogMessage::Flush()
    @     0x7fdb85a14369  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fdb877f5398  stereo::Rectifier::rectifyStereoPair()
    @     0x7fdb877e90af  stereo::Stereo::processStereoFrame()
    @     0x7fdb877ea0ab  stereo::Stereo::addFrame()
    @     0x7fdb877ec98a  stereo::Stereo::addFrames()
    @     0x561a0f0bbcc5  (unknown)
    @     0x7fdb848cdb97  __libc_start_main
    @     0x561a0f0bbe9a  (unknown)

**Comment by immuhammadadil** [comment]
I have successfully loaded the images but there is an issue of "Did not converge with max. iterations." coming up. Image Size is 3000x4000

**Comment by pyn1998** [comment]
> I have successfully loaded the images but there is an issue of "Did not converge with max. iterations." coming up. Image Size is 3000x4000

hi,did you sovled the problem now?could you please tell me how to deal with it?
